## Inicialización de los datos

In [4]:
# Precarga de todas las librerias necesarias para el proyecto

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import TimeSeriesSplit
from sklearn.pipeline import Pipeline
from collections import Counter
from pathlib import Path

In [5]:
# Definición de las rutas de los archivos CSV a utilizar en el proyecto 

base_dir = Path().resolve()

data_path_train = base_dir / 'data' / 'gold_recovery_train.csv'
data_path_test = base_dir / 'data' / 'gold_recovery_test.csv'  
data_path_full = base_dir / 'data' / 'gold_recovery_full.csv'

# Lectura y almacenamiento en dataframes de los CVS proporcionados 

au_list = {
    'au_train': pd.read_csv(data_path_train),
    'au_test': pd.read_csv(data_path_test),
    'au_full': pd.read_csv(data_path_full) }

In [6]:
# Consulta de datos generales au_train, au_test, au_full

for name, df in au_list.items(): 
    print(f'++ Forma de la tabla {name}: {df.shape} ++\n')
    print(df.info())
    print('\n','-'*100,'\n')

++ Forma de la tabla au_train: (16860, 87) ++

<class 'pandas.DataFrame'>
RangeIndex: 16860 entries, 0 to 16859
Data columns (total 87 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   date                                                16860 non-null  str
 1   final.output.concentrate_ag                         16788 non-null  float64
 2   final.output.concentrate_pb                         16788 non-null  float64
 3   final.output.concentrate_sol                        16490 non-null  float64
 4   final.output.concentrate_au                         16789 non-null  float64
 5   final.output.recovery                               15339 non-null  float64
 6   final.output.tail_ag                                16794 non-null  float64
 7   final.output.tail_pb                                16677 non-null  float64
 8   final.output.tail_sol                               16715 non-null  float64
 9   final.output.tail_au                                16794 non-null  float64
 10  primary_cleaner.input.sulfate                       15553 non-null  float64
 11  primary_cleaner.input.depressant                    15598 non-null  float64
 12  primary_cleaner.input.feed_size                     16860 non-null  float64
 13  primary_cleaner.input.xanthate                      15875 non-null  float64
 14  primary_cleaner.output.concentrate_ag               16778 non-null  float64
 15  primary_cleaner.output.concentrate_pb               16502 non-null  float64
 16  primary_cleaner.output.concentrate_sol              16224 non-null  float64
 17  primary_cleaner.output.concentrate_au               16778 non-null  float64
 18  primary_cleaner.output.tail_ag                      16777 non-null  float64
 19  primary_cleaner.output.tail_pb                      16761 non-null  float64
 20  primary_cleaner.output.tail_sol                     16579 non-null  float64
 21  primary_cleaner.output.tail_au                      16777 non-null  float64
 22  primary_cleaner.state.floatbank8_a_air              16820 non-null  float64
 23  primary_cleaner.state.floatbank8_a_level            16827 non-null  float64
 24  primary_cleaner.state.floatbank8_b_air              16820 non-null  float64
 25  primary_cleaner.state.floatbank8_b_level            16833 non-null  float64
 26  primary_cleaner.state.floatbank8_c_air              16822 non-null  float64
 27  primary_cleaner.state.floatbank8_c_level            16833 non-null  float64
 28  primary_cleaner.state.floatbank8_d_air              16821 non-null  float64
 29  primary_cleaner.state.floatbank8_d_level            16833 non-null  float64
 30  rougher.calculation.sulfate_to_au_concentrate       16833 non-null  float64
 31  rougher.calculation.floatbank10_sulfate_to_au_feed  16833 non-null  float64
 32  rougher.calculation.floatbank11_sulfate_to_au_feed  16833 non-null  float64
 33  rougher.calculation.au_pb_ratio                     15618 non-null  float64
 34  rougher.input.feed_ag                               16778 non-null  float64
 35  rougher.input.feed_pb                               16632 non-null  float64
 36  rougher.input.feed_rate                             16347 non-null  float64
 37  rougher.input.feed_size                             16443 non-null  float64
 38  rougher.input.feed_sol                              16568 non-null  float64
 39  rougher.input.feed_au                               16777 non-null  float64
 40  rougher.input.floatbank10_sulfate                   15816 non-null  float64
 41  rougher.input.floatbank10_xanthate                  16514 non-null  float64
 42  rougher.input.floatbank11_sulfate                   16237 non-null  float64
 43  rougher.input.floatbank11_xanthate                  14956 non-null  float64
 44  rougher.output.concentrate_ag                       16778 non-null  float64
 45  rougher.output.concentrate_pb                       16778 non-null  float64
 46  rougher.output.concentrate_sol                      16698 non-null  float64
 47  rougher.output.concentrate_au                       16778 non-null  float64
 48  rougher.output.recovery                             14287 non-null  float64
 49  rougher.output.tail_ag                              14610 non-null  float64
 50  rougher.output.tail_pb                              16778 non-null  float64
 51  rougher.output.tail_sol                             14611 non-null  float64
 52  rougher.output.tail_au                              14611 non-null  float64
 53  rougher.state.floatbank10_a_air                     16807 non-null  float64
 54  rougher.state.floatbank10_a_level                   16807 non-null  float64
 55  rougher.state.floatbank10_b_air                     16807 non-null  float64
 56  rougher.state.floatbank10_b_level                   16807 non-null  float64
 57  rougher.state.floatbank10_c_air                     16807 non-null  float64
 58  rougher.state.floatbank10_c_level                   16814 non-null  float64
 59  rougher.state.floatbank10_d_air                     16802 non-null  float64
 60  rougher.state.floatbank10_d_level                   16809 non-null  float64
 61  rougher.state.floatbank10_e_air                     16257 non-null  float64
 62  rougher.state.floatbank10_e_level                   16809 non-null  float64
 63  rougher.state.floatbank10_f_air                     16802 non-null  float64
 64  rougher.state.floatbank10_f_level                   16802 non-null  float64
 65  secondary_cleaner.output.tail_ag                    16776 non-null  float64
 66  secondary_cleaner.output.tail_pb                    16764 non-null  float64
 67  secondary_cleaner.output.tail_sol                   14874 non-null  float64
 68  secondary_cleaner.output.tail_au                    16778 non-null  float64
 69  secondary_cleaner.state.floatbank2_a_air            16497 non-null  float64
 70  secondary_cleaner.state.floatbank2_a_level          16751 non-null  float64
 71  secondary_cleaner.state.floatbank2_b_air            16705 non-null  float64
 72  secondary_cleaner.state.floatbank2_b_level          16748 non-null  float64
 73  secondary_cleaner.state.floatbank3_a_air            16763 non-null  float64
 74  secondary_cleaner.state.floatbank3_a_level          16747 non-null  float64
 75  secondary_cleaner.state.floatbank3_b_air            16752 non-null  float64
 76  secondary_cleaner.state.floatbank3_b_level          16750 non-null  float64
 77  secondary_cleaner.state.floatbank4_a_air            16731 non-null  float64
 78  secondary_cleaner.state.floatbank4_a_level          16747 non-null  float64
 79  secondary_cleaner.state.floatbank4_b_air            16768 non-null  float64
 80  secondary_cleaner.state.floatbank4_b_level          16767 non-null  float64
 81  secondary_cleaner.state.floatbank5_a_air            16775 non-null  float64
 82  secondary_cleaner.state.floatbank5_a_level          16775 non-null  float64
 83  secondary_cleaner.state.floatbank5_b_air            16775 non-null  float64
 84  secondary_cleaner.state.floatbank5_b_level          16776 non-null  float64
 85  secondary_cleaner.state.floatbank6_a_air            16757 non-null  float64
 86  secondary_cleaner.state.floatbank6_a_level          16775 non-null  float64
dtypes: float64(86), str(1)
memory usage: 11.2 MB
None

 ----------------------------------------------------------------------------------------------------

++ Forma de la tabla au_test: (5856, 53) ++

<class 'pandas.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 53 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date                                        5856 non-null   str
 1   primary_cleaner.input.sulfate               5554 non-null   float64
 2   primary_cleaner.input.depressant            5572 non-null   float64
 3   primary_cleaner.input.feed_size             5856 non-null   float64
 4   primary_cleaner.input.xanthate              5690 non-null   float64
 5   primary_cleaner.state.floatbank8_a_air      5840 non-null   float64
 6   primary_cleaner.state.floatbank8_a_level    5840 non-null   float64
 7   primary_cleaner.state.floatbank8_b_air      5840 non-null   float64
 8   primary_cleaner.state.floatbank8_b_level    5840 non-null   float64
 9   primary_cleaner.state.floatbank8_c_air      5840 non-null   float64
 10  primary_cleaner.state.floatbank8_c_level    5840 non-null   float64
 11  primary_cleaner.state.floatbank8_d_air      5840 non-null   float64
 12  primary_cleaner.state.floatbank8_d_level    5840 non-null   float64
 13  rougher.input.feed_ag                       5840 non-null   float64
 14  rougher.input.feed_pb                       5840 non-null   float64
 15  rougher.input.feed_rate                     5816 non-null   float64
 16  rougher.input.feed_size                     5834 non-null   float64
 17  rougher.input.feed_sol                      5789 non-null   float64
 18  rougher.input.feed_au                       5840 non-null   float64
 19  rougher.input.floatbank10_sulfate           5599 non-null   float64
 20  rougher.input.floatbank10_xanthate          5733 non-null   float64
 21  rougher.input.floatbank11_sulfate           5801 non-null   float64
 22  rougher.input.floatbank11_xanthate          5503 non-null   float64
 23  rougher.state.floatbank10_a_air             5839 non-null   float64
 24  rougher.state.floatbank10_a_level           5840 non-null   float64
 25  rougher.state.floatbank10_b_air             5839 non-null   float64
 26  rougher.state.floatbank10_b_level           5840 non-null   float64
 27  rougher.state.floatbank10_c_air             5839 non-null   float64
 28  rougher.state.floatbank10_c_level           5840 non-null   float64
 29  rougher.state.floatbank10_d_air             5839 non-null   float64
 30  rougher.state.floatbank10_d_level           5840 non-null   float64
 31  rougher.state.floatbank10_e_air             5839 non-null   float64
 32  rougher.state.floatbank10_e_level           5840 non-null   float64
 33  rougher.state.floatbank10_f_air             5839 non-null   float64
 34  rougher.state.floatbank10_f_level           5840 non-null   float64
 35  secondary_cleaner.state.floatbank2_a_air    5836 non-null   float64
 36  secondary_cleaner.state.floatbank2_a_level  5840 non-null   float64
 37  secondary_cleaner.state.floatbank2_b_air    5833 non-null   float64
 38  secondary_cleaner.state.floatbank2_b_level  5840 non-null   float64
 39  secondary_cleaner.state.floatbank3_a_air    5822 non-null   float64
 40  secondary_cleaner.state.floatbank3_a_level  5840 non-null   float64
 41  secondary_cleaner.state.floatbank3_b_air    5840 non-null   float64
 42  secondary_cleaner.state.floatbank3_b_level  5840 non-null   float64
 43  secondary_cleaner.state.floatbank4_a_air    5840 non-null   float64
 44  secondary_cleaner.state.floatbank4_a_level  5840 non-null   float64
 45  secondary_cleaner.state.floatbank4_b_air    5840 non-null   float64
 46  secondary_cleaner.state.floatbank4_b_level  5840 non-null   float64
 47  secondary_cleaner.state.floatbank5_a_air    5840 non-null   float64
 48  secondary_cleaner.state.floatbank5_a_level  5840 non-null   float64
 49  secondary_cleaner.state.floatbank5_b_air    5840 non-null   float64
 50  secondary_cleaner.state.floatbank5_b_level  5840 non-null   float64
 51  secondary_cleaner.state.floatbank6_a_air    5840 non-null   float64
 52  secondary_cleaner.state.floatbank6_a_level  5840 non-null   float64
dtypes: float64(52), str(1)
memory usage: 2.4 MB
None

 ----------------------------------------------------------------------------------------------------

++ Forma de la tabla au_full: (22716, 87) ++

<class 'pandas.DataFrame'>
RangeIndex: 22716 entries, 0 to 22715
Data columns (total 87 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   date                                                22716 non-null  str
 1   final.output.concentrate_ag                         22627 non-null  float64
 2   final.output.concentrate_pb                         22629 non-null  float64
 3   final.output.concentrate_sol                        22331 non-null  float64
 4   final.output.concentrate_au                         22630 non-null  float64
 5   final.output.recovery                               20753 non-null  float64
 6   final.output.tail_ag                                22633 non-null  float64
 7   final.output.tail_pb                                22516 non-null  float64
 8   final.output.tail_sol                               22445 non-null  float64
 9   final.output.tail_au                                22635 non-null  float64
 10  primary_cleaner.input.sulfate                       21107 non-null  float64
 11  primary_cleaner.input.depressant                    21170 non-null  float64
 12  primary_cleaner.input.feed_size                     22716 non-null  float64
 13  primary_cleaner.input.xanthate                      21565 non-null  float64
 14  primary_cleaner.output.concentrate_ag               22618 non-null  float64
 15  primary_cleaner.output.concentrate_pb               22268 non-null  float64
 16  primary_cleaner.output.concentrate_sol              21918 non-null  float64
 17  primary_cleaner.output.concentrate_au               22618 non-null  float64
 18  primary_cleaner.output.tail_ag                      22614 non-null  float64
 19  primary_cleaner.output.tail_pb                      22594 non-null  float64
 20  primary_cleaner.output.tail_sol                     22365 non-null  float64
 21  primary_cleaner.output.tail_au                      22617 non-null  float64
 22  primary_cleaner.state.floatbank8_a_air              22660 non-null  float64
 23  primary_cleaner.state.floatbank8_a_level            22667 non-null  float64
 24  primary_cleaner.state.floatbank8_b_air              22660 non-null  float64
 25  primary_cleaner.state.floatbank8_b_level            22673 non-null  float64
 26  primary_cleaner.state.floatbank8_c_air              22662 non-null  float64
 27  primary_cleaner.state.floatbank8_c_level            22673 non-null  float64
 28  primary_cleaner.state.floatbank8_d_air              22661 non-null  float64
 29  primary_cleaner.state.floatbank8_d_level            22673 non-null  float64
 30  rougher.calculation.sulfate_to_au_concentrate       22672 non-null  float64
 31  rougher.calculation.floatbank10_sulfate_to_au_feed  22672 non-null  float64
 32  rougher.calculation.floatbank11_sulfate_to_au_feed  22672 non-null  float64
 33  rougher.calculation.au_pb_ratio                     21089 non-null  float64
 34  rougher.input.feed_ag                               22618 non-null  float64
 35  rougher.input.feed_pb                               22472 non-null  float64
 36  rougher.input.feed_rate                             22163 non-null  float64
 37  rougher.input.feed_size                             22277 non-null  float64
 38  rougher.input.feed_sol                              22357 non-null  float64
 39  rougher.input.feed_au                               22617 non-null  float64
 40  rougher.input.floatbank10_sulfate                   21415 non-null  float64
 41  rougher.input.floatbank10_xanthate                  22247 non-null  float64
 42  rougher.input.floatbank11_sulfate                   22038 non-null  float64
 43  rougher.input.floatbank11_xanthate                  20459 non-null  float64
 44  rougher.output.concentrate_ag                       22618 non-null  float64
 45  rougher.output.concentrate_pb                       22618 non-null  float64
 46  rougher.output.concentrate_sol                      22526 non-null  float64
 47  rougher.output.concentrate_au                       22618 non-null  float64
 48  rougher.output.recovery                             19597 non-null  float64
 49  rougher.output.tail_ag                              19979 non-null  float64
 50  rougher.output.tail_pb                              22618 non-null  float64
 51  rougher.output.tail_sol                             19980 non-null  float64
 52  rougher.output.tail_au                              19980 non-null  float64
 53  rougher.state.floatbank10_a_air                     22646 non-null  float64
 54  rougher.state.floatbank10_a_level                   22647 non-null  float64
 55  rougher.state.floatbank10_b_air                     22646 non-null  float64
 56  rougher.state.floatbank10_b_level                   22647 non-null  float64
 57  rougher.state.floatbank10_c_air                     22646 non-null  float64
 58  rougher.state.floatbank10_c_level                   22654 non-null  float64
 59  rougher.state.floatbank10_d_air                     22641 non-null  float64
 60  rougher.state.floatbank10_d_level                   22649 non-null  float64
 61  rougher.state.floatbank10_e_air                     22096 non-null  float64
 62  rougher.state.floatbank10_e_level                   22649 non-null  float64
 63  rougher.state.floatbank10_f_air                     22641 non-null  float64
 64  rougher.state.floatbank10_f_level                   22642 non-null  float64
 65  secondary_cleaner.output.tail_ag                    22616 non-null  float64
 66  secondary_cleaner.output.tail_pb                    22600 non-null  float64
 67  secondary_cleaner.output.tail_sol                   20501 non-null  float64
 68  secondary_cleaner.output.tail_au                    22618 non-null  float64
 69  secondary_cleaner.state.floatbank2_a_air            22333 non-null  float64
 70  secondary_cleaner.state.floatbank2_a_level          22591 non-null  float64
 71  secondary_cleaner.state.floatbank2_b_air            22538 non-null  float64
 72  secondary_cleaner.state.floatbank2_b_level          22588 non-null  float64
 73  secondary_cleaner.state.floatbank3_a_air            22585 non-null  float64
 74  secondary_cleaner.state.floatbank3_a_level          22587 non-null  float64
 75  secondary_cleaner.state.floatbank3_b_air            22592 non-null  float64
 76  secondary_cleaner.state.floatbank3_b_level          22590 non-null  float64
 77  secondary_cleaner.state.floatbank4_a_air            22571 non-null  float64
 78  secondary_cleaner.state.floatbank4_a_level          22587 non-null  float64
 79  secondary_cleaner.state.floatbank4_b_air            22608 non-null  float64
 80  secondary_cleaner.state.floatbank4_b_level          22607 non-null  float64
 81  secondary_cleaner.state.floatbank5_a_air            22615 non-null  float64
 82  secondary_cleaner.state.floatbank5_a_level          22615 non-null  float64
 83  secondary_cleaner.state.floatbank5_b_air            22615 non-null  float64
 84  secondary_cleaner.state.floatbank5_b_level          22616 non-null  float64
 85  secondary_cleaner.state.floatbank6_a_air            22597 non-null  float64
 86  secondary_cleaner.state.floatbank6_a_level          22615 non-null  float64
dtypes: float64(86), str(1)
memory usage: 15.1 MB
None

 ----------------------------------------------------------------------------------------------------

In [7]:
# Impresion de muestra de au_train, au_test, au_full

for df in au_list: display(au_list[df].sample(3))

,date,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
9259,2017-06-05 18:59:59,4.251917,10.636725,8.076898,46.022685,61.144151,8.937325,3.593877,9.165263,3.667957,...,14.974680,-496.825926,9.969688,-379.003796,14.973678,-499.202633,9.993810,-500.127585,14.998421,-500.180405
13156,2018-03-17 03:59:59,4.981612,11.343507,7.925563,44.042980,72.190053,10.007210,2.568092,8.326815,2.762034,...,23.034590,-499.658962,14.964297,-499.602745,18.044661,-499.781130,11.981768,-500.055758,11.978576,-500.129242
6749,2017-02-21 04:59:59,5.813475,10.747704,14.104161,43.976033,73.010765,12.094983,4.189077,8.629817,3.733846,...,24.989349,-399.064774,23.012468,-400.162613,22.998051,-449.256157,19.982860,-449.842581,24.984365,-499.666109

,date,primary_cleaner.input.sulfate,primary_cleaner.input.depressant,primary_cleaner.input.feed_size,primary_cleaner.input.xanthate,primary_cleaner.state.floatbank8_a_air,primary_cleaner.state.floatbank8_a_level,primary_cleaner.state.floatbank8_b_air,primary_cleaner.state.floatbank8_b_level,primary_cleaner.state.floatbank8_c_air,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
4148,2017-10-21 20:59:59,225.958287,13.960422,7.10,1.829708,1699.849346,-499.290150,1700.946299,-486.490115,1654.767808,...,21.000713,-501.216740,19.004196,-401.031767,15.031874,-500.511709,10.980509,-500.103418,16.007900,-500.236458
2003,2016-11-23 11:59:59,196.041197,6.963809,7.38,1.696760,1596.746210,-499.806829,1602.025873,-500.232514,1599.470762,...,18.030640,-501.135997,15.882575,-447.343029,15.395065,-499.946950,11.959839,-500.014192,21.968055,-499.210981
5425,2017-12-14 01:59:59,196.524958,9.989526,8.19,1.100436,1554.171896,-500.106363,1547.485556,-497.016248,1548.260337,...,20.006407,-500.873491,15.048109,-113.572960,10.999067,-499.975324,8.048825,-500.181578,11.990546,-499.904981

,date,final.output.concentrate_ag,final.output.concentrate_pb,final.output.concentrate_sol,final.output.concentrate_au,final.output.recovery,final.output.tail_ag,final.output.tail_pb,final.output.tail_sol,final.output.tail_au,...,secondary_cleaner.state.floatbank4_a_air,secondary_cleaner.state.floatbank4_a_level,secondary_cleaner.state.floatbank4_b_air,secondary_cleaner.state.floatbank4_b_level,secondary_cleaner.state.floatbank5_a_air,secondary_cleaner.state.floatbank5_a_level,secondary_cleaner.state.floatbank5_b_air,secondary_cleaner.state.floatbank5_b_level,secondary_cleaner.state.floatbank6_a_air,secondary_cleaner.state.floatbank6_a_level
19629,2018-04-11 20:59:59,3.542927,9.394940,8.080893,49.219810,72.566337,9.225082,2.123326,7.546866,1.859629,...,23.008370,-501.063222,15.939196,-341.002660,17.952079,-499.945497,12.062322,-499.601582,12.996949,-500.068713
1708,2016-03-26 04:00:00,5.108435,8.708830,1.702668,48.109180,62.287500,10.189546,1.233996,18.874992,2.847869,...,11.956652,-500.525189,11.954754,-500.054336,12.039793,-499.542724,10.021443,-499.873688,19.985900,-500.144534
16858,2017-12-17 09:59:59,7.506471,9.247625,8.265027,28.575838,29.950111,9.377262,1.431288,4.904435,4.025224,...,19.957843,-498.201601,16.074490,-44.244302,11.027198,-497.421379,7.997135,-499.712718,12.001879,-499.602975

In [8]:
# Funcion para limpiar dataframes

def wrangling(data):

    '''
    Consulta la cantidad de celdas vacias y duplicadas del dataframe brindado,
    posteriormente se eliminan las filas con estos datos
    '''

    dup = data.duplicated().sum()
    null = data.isna().sum().sum()
    
    if null > 0: data = data.dropna()

    if dup > 0: data.drop_duplicates().reset_index()

    return data

In [9]:
# Comprobacion de datos faltantes y duplicados en au_train, au_test, au_full

print(f"** Dataframes sin limpiar")
for name, df in au_list.items():
    print('-'*40)
    print(name)
    print(f'+ Forma de la tabla: {df.shape}\n+ Duplicados: {df.duplicated().sum()}\n+ Celdas vacias: {df.isna().sum().sum()}\n')
    print('-'*40)

# Llamado de la funcion wrangling para limpiar au_train, au_test, au_full

au_list_cl = {name: wrangling(df) for name, df in au_list.items()}

# Confirmacion de limpieza

print(f"** Dataframes limpios")
for name, df in au_list_cl.items():
    print('-'*40)
    print(name)
    print(f'+ Forma de la tabla: {df.shape}\n+ Duplicados: {df.duplicated().sum()}\n+ Celdas vacias: {df.isna().sum().sum()}\n')
    print('-'*40)

** Dataframes sin limpiar
----------------------------------------
au_train
+ Forma de la tabla: (16860, 87)
+ Duplicados: 0
+ Celdas vacias: 30320

----------------------------------------
----------------------------------------
au_test
+ Forma de la tabla: (5856, 53)
+ Duplicados: 0
+ Celdas vacias: 2360

----------------------------------------
----------------------------------------
au_full
+ Forma de la tabla: (22716, 87)
+ Duplicados: 0
+ Celdas vacias: 36587

----------------------------------------
** Dataframes limpios
----------------------------------------
au_train
+ Forma de la tabla: (11017, 87)
+ Duplicados: 0
+ Celdas vacias: 0

----------------------------------------
----------------------------------------
au_test
+ Forma de la tabla: (5383, 53)
+ Duplicados: 0
+ Celdas vacias: 0

----------------------------------------
----------------------------------------
au_full
+ Forma de la tabla: (16094, 87)
+ Duplicados: 0
+ Celdas vacias: 0

----------------------------------------